### ISSUE TITLE
Problems with installation -- requires many packages, and vignette installation fails

### ISSUE THREAD

**Issue by lhenneman** [garbulinskamaja/disperseR#20]
For installation, I had to install knitr, downloader, and rmarkdown, tidyverse, sf, ggsn, viridis, and ggrepel packages. 

In the end, vignette builds failed because "'create_dirs' is not an exported object from 'namespace:disperseR'". @garbulinskamaja is this an issue with not having the directory structure already set when I install it the first time?

**Comment by garbulinskamaja** [comment]
These packages are in suggested. I will move them to depends and I hope this solves the issue. No. The directory structure should be created automatically. I have been having the same error with create_dirs and I can't figure out why. Never happened before.

**Comment by garbulinskamaja** [comment]
The vignettes work now when trying to build. I am still trying to figure out what has happened with the namespace error.

**Comment by garbulinskamaja** [comment]
this should work now

**Comment by lhenneman** [comment]
Bad news - this still fails for me: devtools::install_github("lhenneman/disperseR@majadev", force = TRUE, build_vignettes = TRUE). Still getting this:

  Quitting from lines 92-93 (Vignette_Get_Data_One_by_One.Rmd) 
   Error: processing vignette 'Vignette_Get_Data_One_by_One.Rmd' failed with diagnostics:
   'get_data' is not an exported object from 'namespace:disperseR'
   --- failed re-building ‘Vignette_Get_Data_One_by_One.Rmd’

**Comment by garbulinskamaja** [comment]
oh dear. First time I have been using roxygen2. It is tricky. I will fix it.

**Comment by garbulinskamaja** [comment]
i fixed it and tested it and it worked on my computer. Hope it works.

**Comment by cchoirat** [comment]
You can/should set up a CI, for example: https://docs.travis-ci.com/user/languages/r/.

**Comment by munshimdrasel** [comment]
I get the following error after I run the installation code "devtools::install_github("lhenneman/disperseR", force = TRUE, build_vignettes = TRUE)"
Before that, I've already installed Rcpp, downloader, and tidyverse package.

"Error: Failed to install 'disperseR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> --- finished re-building ‘Vignette_ZCTA_Shapefile_Preparation.Rmd’
E> 
E> --- re-building ‘Vignette_Zip_Code_Coordinate_Data_Preparation.Rmd’ using rmarkdown
E> --- finished re-building ‘Vignette_Zip_Code_Coordinate_Data_Preparation.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘Vignette_DisperseR.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted"

**Comment by munshimdrasel** [comment]
For installation, I had to install Rcpp, downloader, rgdal and SplitR packages:

install.packages(c("Rcpp", "downloader", "rgdal"))
devtools::install_github("lhenneman/SplitR", force = TRUE)

**Comment by audiracmichelle** [comment]
I installed on Apple Silicon (MacBook Air M1). To do this I used `devtools::install_github("lhenneman/disperseR"` (remove force and build_vignettes) and answer no when `Do you want to install from sources the package which needs compilation? (Yes/no/cancel) no` is prompted
